################################################################################
#
# Method to create a constraint matrix for shape-constrained splines
# Works with various type of splines found in R.
#
################################################################################

#' Create shape constraints
#'
#' @description
#' Creates a constraint matrix to shape-constrain a set of coefficients. Mainly intended for splines but can constrain various bases or set of variables. Will typically be called from within [cirls.fit][cirls.fit()] but can be used to generate constraint matrices.
#'
#' @param x An object representing a design matrix of predictor variables, typically basis functions. See details for supported objects.
#' @param shape A character vector indicating one or several shape-constraints. See details for supported shapes.
#' @param intercept For some methods, a logical value indicating if the design matrix includes an intercept. In most cases will be automatically extracted from `x`.
#' @param ... Additional parameters passed to or from other methods.
#'
#' @details
#' The recommended usage is to directly specify the shape constraint through the `shape` argument in the call to [glm][stats::glm()] with [cirls.fit][cirls.fit()]. This method is then called internally to create the constraint matrix. However, `shapeConstr` can nonetheless be called directly to manually build or inspect the constraint matrix for a given shape and design matrix.
#'
#' The `shape` argument allows to define a specific shape for the association between the expanded term in `x` and the response of the regression model. This shape can describe the relation between coefficients for the default method, or the shape of the smooth term for spline bases. At the moment, six different shapes are supported by the `shape` argument:
#' \describe{
#'   \item{`"pos"`}{Positive.}
#'   \item{`"neg"`}{Negative.}
#'   \item{`"inc"`}{Monotonically increasing.}
#'   \item{`"dec"`}{Monotonically decreasing.}
#'   \item{`"cvx"`}{Convex.}
#'   \item{`"ccv"`}{Concave.}
#' }
#'
#' When consistent, several shapes can be provided simultaneously to obtain, e.g., a monotone increasing and convex association.
#'
#' `shapeConstr` currently supports several objects, creating an appropriate shape-constraint matrix depending on the object:
#' \describe{
#'   \item{`default`}{The default method takes any design matrix and creates a constraint matrix for the shape on the coefficients. For instance, `shape = "inc"` will ensure that the coefficients associated with each variable in `x` is greater or equal than the coeffients of the previous columns. The default method includes an additional argument `intercept` (see below).}
#'   \item{`bs`}{B-spline bases as generated from the [bs][splines::bs()] function from the `splines` package. Works for any spline order and knot specification.}
#'   \item{`ns`}{Natural splines as generated from the [ns][splines::ns()] function from the `splines` package. Similar to [bs][splines::bs()] but accounting for the linearity constraints at the boundaries.}
#'   \item{`ps`}{Penalised splines (P-Splines) as generated by the [ps][dlnm::ps()] function from the `dlnm` package.}
#'   \item{`onebasis`}{General method for basis functions generated by [onebasis][dlnm::onebasis()] from the `dlnm` package. Will typically call the appropriate method depending on the `fun` argument.}
#' }
#'
#' The parameters necessary to build the constraint matrix (e.g. `knots` and `ord` for splines) are typically extracted from the `x` object. This is also true for the `intercept` for most of the object, except for the default method for which it can be useful to explicitly provide it. In a typical usage in which `shapeConstr` would only be called within [cirls.fit][cirls.fit()], `intercept` is automatically determined from the [glm][stats::glm()] formula.
#'
#' @returns A constraint matrix to be passed to `Cmat` in [cirls.fit][cirls.fit()].
#'
#' @references
#' Zhou, S. & Wolfe, D. A., 2000, On derivative estimation in spline regression. *Statistica Sinica* **10**, **93–108**.
#'
#' @seealso [cirls.fit()] which typically calls `shapeConstr` internally.
#'
#' @examples
#' # example code
#'
#'
#' @export
shapeConstr <- function(x, shape, ...) UseMethod("shapeConstr")
